### ISSUE TITLE
Incomplete HTML question

### ISSUE THREAD

**Issue by Ezzu99** [rabiayousuf187/Online-Quiz-WebApp-06Mar2023#1]
HTML question number 8 should specify the type of input, i.e "email."

**Comment by rabiayousuf187** [comment]
> HTML question number 8 should specify the type of input, i.e "email."

Thank you for the cooperation, let me check.

**Comment by rabiayousuf187** [comment]
> HTML question number 8 should specify the type of input, i.e "email."
As **Question 8,  Which of the following is an example of a new form input type in HTML5?** It is a little bit tricky, and its explaination is: HTML 5 introduces several input types like Date, DateTime, DateTime-local, time, week, month, email, tel, URL, search, range, color, and number to improve the user experience and to make the forms more interactive. 
However, if a browser fails to recognize these new input types, it will treat them like a normal text box.

**Comment by rabiayousuf187** [comment]
> HTML question number 8 should specify the type of input, i.e "email."

As **Question 8,  Which of the following is an example of a new form input type in HTML5?** It is a little bit tricky, and its explanation is: HTML 5 introduces several input types like Date, DateTime, DateTime-local, time, week, month, email, tel, URL, search, range, color, and number to improve the user experience and to make the forms more interactive. 
However, if a browser fails to recognize these new input types, it will treat them like a normal text box.

I hope  this explanation will be helpful to you.

**Comment by Ezzu99** [comment]
The question seemed a bit ambiguous to me. It should be like "Which of the following input type was introduced in HTML 5?" Instead of using the word "new" in the question.

**Comment by rabiayousuf187** [comment]
> The question seemed a bit ambiguous to me. It should be like "Which of the following input type was introduced in HTML 5?" Instead of using the word "new" in the question.

@Ezzu99, Yes, It can be possible.
Would you like to share your your experience and score on linkedIn regarding QWA, if it  is  convinent for you.

Thanks for your cooperation.
